[APPS-3168]- Shake report pod changes to support iOS send feedback Se…
papiguy/ShakeReport pull request #1
Opened 2019-01-31 23:22 UTC by snehaViewGlass

…ndgrid redesign

2019-01-31 23:29 UTC, tdaniel-vg requested changes

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.h
> +@class SRReporter;
remove

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +        _sendFeedback = NO;
remove

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +    //return !_composerDisplayed && [MFMailComposeViewController canSendMail];
return delegate != nil || !_composerDisplayed && [MFMailComposeViewController canSendMail]

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +        //[self showMailComposer:attachImage];
if (delegate == nil) { [self showMailComposer:attachImage];
else {
 //do your thing
}

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +- (void) sendFeedbackMailComposer:(BOOL)attachImage {
no need for this function now

2019-01-31 23:29 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +    NSData *imageData;
set to nil.

2019-02-01 00:19 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +- (void) sendFeedbackMailComposer:(BOOL)attachImage {
removed the below function

2019-02-01 00:20 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.h
> +@class SRReporter;
removed

2019-02-01 00:20 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +    //return !_composerDisplayed && [MFMailComposeViewController canSendMail];
changed this

2019-02-01 00:20 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +    NSData *imageData;
set to nil

2019-02-06 23:13 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +        //[self showMailComposer:attachImage];
changed it

2019-02-06 23:13 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +        _sendFeedback = NO;
removed

2019-02-06 23:14 UTC, tdaniel-vg approved these changes

2019-02-06 23:14 UTC, tdaniel-vg commented on ShakeReport/Library/SRReporter.m
> +    return _delegate!= nil || (!_composerDisplayed && [MFMailComposeViewController canSendMail]);
_delegate<space> != nil

2019-02-06 23:28 UTC, snehaViewGlass commented on ShakeReport/Library/SRReporter.m
> +    return _delegate!= nil || (!_composerDisplayed && [MFMailComposeViewController canSendMail]);
changed it

2019-02-06 23:31 UTC, merged